version: "3.5"

services:
    web:
        image: bref/fpm-dev-gateway
        ports:
            - '5000:80'
        volumes:
            - .:/var/task:ro
            - ./cache:/var/task/cache
        depends_on:
            - php
        environment:
            HANDLER: public/index.php
            DOCUMENT_ROOT: public
    php:
        image: bref/php-74-fpm-dev
        volumes:
            - .:/var/task
      